### PR TITLE
virustotalv3:feature - add reputation checks cache

### PR DESCRIPTION
**Pull request by jang-splunk**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [x] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

There is now the option of caching the results of reputation checks actions.

- In the asset configuration page, there are three(3) new options.
   - boolean - "cache_reputation_checks" - enables or disable caching
   - numeric - "cache_expiration_interval" - how many seconds until the cached entry expires and is purged
   - numeric - "cache_size" - maximum number of entries in cache

  Cached entries are stored in the asset state file across invocations, so management of the cache_expiration_interval and 
  cache_size is important. If the cache grows too large it will affect execution times of the app actions.

  Two new actions are provided:
  - clear cache- purges all entries. from the cache
  - get cached entries - reports back the state of the cache

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

all reputation checks 

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

add caching of virustotalv3 reputation check results

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by ighelani-crest** [comment]
Hi @jang-splunk ,
I have seen the following things for url reputation in your PR action.
when you run url reputation action for any url then first it will encode the URL and then make_rest_call method will be called so it will store the encoded value of URL in the cache. if get cache entries action is called then it will take the encoded value and show it on UI (which i guess you can show the original value). 
FYI: you are storing the cache in a state file of an asset if an asset is changed then you will not be able to get the data via the get cache entries action.

**Comment by jang-splunk** [comment]
>  FYI: you are storing the cache in a state file of an asset if an asset is changed then you will not be able to get the data via the get cache entries action.

I haven't consider that detail, but the current method is fine;  I don't expect a lot of sites would use multiple assets for the same purpose  (ie. same set of iocs, same cache expiration times). .. In any case, using an external file will require adding code to avoid race conditions and additional complexities are not really desirable. If time-to-run is greatly increased, then we should consider using some different backing mechanism, such as a hashed db.

**Comment by jang-splunk** [comment]
> when you run url reputation action for any url then first it will encode the URL and then make_rest_call method will be called so it will store the encoded value of URL in the cache. if get cache entries action is called then it will take the encoded value and show it on UI (which i guess you can show the original value).

This is not quite correct. When a reputation call is made, the IOC is checked for an unexpired entry in the cache and returned if found. If an entry is not found, it will call virustotal for a reputation check and store the new results into the cache before returning the result to the action.

The "get cached entries" action is used to examine the entries in the cache and does not return the reputation results

**Comment by ighelani-crest** [comment]
Hi @jang-splunk,
I just wanted to confirm with you that when you run get_cached_entries after running url_repuation for (www.ibm.com) then it will show the following output (d3d3LmlibS5jb20 instead of www.ibm.com). is that look good to you?
Screenshot 2023-03-15 at 11 37 00 AM
but for another action like when you run get_cached_entries after running domain_reputation for (www.ibm.com) then it will show the following output.
image

**Comment by jang-splunk** [comment]
Ah. No, it looks like it needs to un-encode the endpoint. I'll take care of it later today. Thanks for noticing it.

**Comment by ighelani-crest** [comment]
Hi @jang-splunk,
can you provide me some Est. Timing that when you will commit the code for handling url reputation?

**Comment by ighelani-crest** [comment]
@jang-splunk 
I am adding the check for the "URL reputation" app.
please let me know if you have any concern.

**Review by alexa-phantom — APPROVED** [review]

**Comment by ricardo-phantom** [comment]
Please have passing Static Test pipeline before merging. Thanks.

**Review by ishans-crest — APPROVED** [review]

**Pull request merged**
